on:
  pull_request_review_comment:
    types: [ created, deleted ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Checkout Code
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
  set_value:
    runs-on: ubuntu-latest
    name: Get User Name
    outputs:
      matrix: ${{ steps.json_properties.outputs.* }}
    steps:
      - name: get properties
        id: json_properties
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: "../slack-id.json"
  slack:
    runs-on: ubuntu-latest
    name: Send Slack Notification
    steps:
      - name: Send GitHub trigger payload to Slack Workflow Builder
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
            "text": "PR Raised by: ${{ github.event.pull_request.actor }}\n Comment : ${{ github.event.comment.body }} \n Comment AddedBy: ${{ github.event.comment.user.login }} \n Comment URL: ${{ github.event.comment.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_2 }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

#
#jobs:
#  pr-message-to-slack:
#    runs-on: ubuntu-latest
#    steps:
#      # To use slack-id.json
#      - uses: actions/checkout@v2
#      - uses: hirokisakabe/pr-message-to-slack@v1.0.0
#        env:
#          # https://hooks.slack.com/...
#          PR_MESSAGE_SLACK_WEBHOOK_URL: ${{ secrets.PR_MESSAGE_SLACK_WEBHOOK_URL }}