on:
  pull_request_review_comment:
    types: [ created, deleted ]

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
      - name: Send GitHub trigger payload to Slack Workflow Builder
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
            "text": "Comment : ${{ github.event.comment.body }} \n AddedBy: ${{ github.event.comment.user.login }} \n PR: ${{ github.event.comment.html_url }}",
            "channel": "dpnkvrm"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_2 }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK