on:
  pull_request_review_comment:
    types:
      - created
      - deleted
jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Checkout Code
    outputs:
      user: ${{ steps.set_command.outputs.user }}
    steps:
      - uses: actions/checkout@v2
      - id: set_command
        run: |
          content=`cat .github/slack-id.json`
          echo $content
          echo ${{ github.event.pull_request.user.login }}
          echo $content | jq .${{ github.event.pull_request.user.login }}
          echo "::set-output name=user::$content"

  slack:
    runs-on: ubuntu-latest
    name: Send Slack Notification
    steps:
     - name: Send GitHub trigger payload to Slack Workflow Builder
       id: slack
       uses: slackapi/slack-github-action@v1.23.0
       with:
         payload: |
           {
           "text": "PR Raised by: ${{ github.event.pull_request.user.login }}\n Comment : ${{ github.event.comment.body }} \n Comment AddedBy: ${{ github.event.comment.user.login }} \n Comment URL: ${{ github.event.comment.html_url }}",
           "channel": "${{ needs.checkout.outputs.user}}"
           }
       env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
