on:
  pull_request:
    # 'types' only supports 'review_requested'
    types: [review_requested]

# Prevent sending multiple messages when there are multiple reviewers.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pr-message-to-slack:
    runs-on: ubuntu-latest
    steps:
      # To use slack-id.json
      - uses: actions/checkout@v2
      - uses: hirokisakabe/pr-message-to-slack@v1.0.0
        env:
          # https://hooks.slack.com/...
          PR_MESSAGE_SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/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'
