on:
  pull_request_review_comment:
    types: [ created, deleted ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Checkout Code
    steps:
      - uses: actions/checkout@v2
        with:
          path: './'
      - id: set_var
        run: |
          content=`cat .github/slack-id.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          username=${{ github.event.pull_request.actor }}
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
          echo ${{ github.event.pull_request.actor }}
      - run: |
          source $GITHUB_ENV
          env
          VAR="steps.set_var.outputs.packageJson"
          VAR1="$VAR"
          echo "fromJSON($VAR1."${{ github.event.pull_request.actor }}")"

#  set_value:
#    runs-on: ubuntu-latest
#    name: Get User Name
##    outputs:
##      matrix: ${{ steps.json_properties.outputs.* }}
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          path: './'
#      - name: get properties
#        id: json_properties
#        uses: zoexx/github-action-json-file-properties@release
#        with:
#          file_path: ".github/slack-id.json"
#      - run: |
#          echo "${{ steps.json_properties.outputs.*.dpnkvrm }}"
#          echo "${{ format('{0}.{1}', steps.json_properties, github.event.pull_request.actor) }}"
  slack:
    runs-on: ubuntu-latest
    name: Send Slack Notification
    steps:
      - name: Send GitHub trigger payload to Slack Workflow Builder
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
            "text": "PR Raised by: ${{ github.event.pull_request.actor }}\n Comment : ${{ github.event.comment.body }} \n Comment AddedBy: ${{ github.event.comment.user.login }} \n Comment URL: ${{ github.event.comment.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_2 }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - name: print env
        run: |
          echo ${{ github.event.pull_request.actor }}

#
#jobs:
#  pr-message-to-slack:
#    runs-on: ubuntu-latest
#    steps:
#      # To use slack-id.json
#      - uses: actions/checkout@v2
#      - uses: hirokisakabe/pr-message-to-slack@v1.0.0
#        env:
#          # https://hooks.slack.com/...
#          PR_MESSAGE_SLACK_WEBHOOK_URL: ${{ secrets.PR_MESSAGE_SLACK_WEBHOOK_URL }}