on:
  pull_request_review_comment:
    types: [ created, deleted ]
#concurrency:
#  group: ${{ github.head_ref || github.run_id }}
#  cancel-in-progress: true

jobs:
  testJob:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: set_id
        run: |
          content=`cat ../slack-id.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
      - run: |
          echo "${{fromJson(steps.set_id.outputs.packageJson).{{ github.event.pull_request.user.login }}}}"
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
      - name: Send GitHub trigger payload to Slack Workflow Builder
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
            "text": "PR Raised by: ${{ github.event.pull_request.user.login }}\n Comment : ${{ github.event.comment.body }} \n Comment AddedBy: ${{ github.event.comment.user.login }} \n Comment URL: ${{ github.event.comment.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_2 }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

#
#jobs:
#  pr-message-to-slack:
#    runs-on: ubuntu-latest
#    steps:
#      # To use slack-id.json
#      - uses: actions/checkout@v2
#      - uses: hirokisakabe/pr-message-to-slack@v1.0.0
#        env:
#          # https://hooks.slack.com/...
#          PR_MESSAGE_SLACK_WEBHOOK_URL: ${{ secrets.PR_MESSAGE_SLACK_WEBHOOK_URL }}